[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version="0.8.8", features = ["ws"] }
chrono = { version = "0.4.44", features = ["serde"] }
futures-util = "0.3.32"
hyper = { version = "1.8.1", features = ["full"] }
livekit = "0.7.40"
livekit-api = "0.4.23"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "macros", "chrono"] }
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["full"] }
tower = "0.5.3"
tower-http = { version="0.6.8", features=["cors"] }

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }

[dependencies.uuid]
version = "1.23.0"
# Lets you generate random UUIDs
features = [
    "v4",
]
