services:
  app:
    container_name: server
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://antihype:An!?h3p37!W.W@db:5432/qorthone_api
  db:
    image: postgres:15
    container_name: quorthon_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: antihype
      POSTGRES_PASSWORD: An!?h3p37!W.W
      POSTGRES_DB: quorthon_api
    volumes:
      - quorthon_data:/var/lib/postgresql/data

volumes:
  quorthon_data: