services:
  app:
    container_name: server
    build: .
    expose:
      - "3000"
    depends_on:
      - livekit
    environment:
      DATABASE_URL: postgres://antihype:W440Qh6qWJ5JsY184@quorthon_db:5432/quorthon_api
      LIVEKIT_URL: ws://livekit:7880
      LIVEKIT_API_KEY: quorthon_key
      LIVEKIT_API_SECRET: mP9vkR==zvRN8vZHpH7kxXf5jpPhWfm4I=49RyWk
  db:
    image: postgres:15
    container_name: quorthon_db
    environment:
      POSTGRES_USER: antihype
      POSTGRES_PASSWORD: W440Qh6qWJ5JsY184
      POSTGRES_DB: quorthon_api
    volumes:
      - quorthon_data:/var/lib/postgresql/data
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50050:50000-50050/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    command: --config /etc/livekit.yaml
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=quorthon.eu
    depends_on:
      - app
volumes:
  quorthon_data:
  caddy_data:
  caddy_config: