services:
  app:
    container_name: server
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://antihype:W440Qh6qWJ5JsY184@quorthon_db:5432/quorthon_api
  db:
    image: postgres:15
    container_name: quorthon_db
    environment:
      POSTGRES_USER: antihype
      POSTGRES_PASSWORD: W440Qh6qWJ5JsY184 # ! - %21, ? - %3F
      POSTGRES_DB: quorthon_api
    volumes:
      - quorthon_data:/var/lib/postgresql/data

volumes:
  quorthon_data: